FROM eclipse-temurin:17-jdk-jammy AS builder
WORKDIR /app
COPY . .
RUN ./gradlew :test-module:installDist --no-daemon

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /app/test-module/build/install/test-module /app/test-module
COPY --from=builder /app/journal-web /app/journal-web

# Run the application distribution script generated by Gradle application plugin
CMD ["/app/test-module/bin/test-module"]
