[versions]
kotlin = "2.1.20"
gson = "2.14.0"
jackson = "2.22.2"
ta4j = "0.16"
commonsMath = "3.6.1"
dataframe = "0.15.0"
xchart = "4.0.4"
coroutines = "1.11.0"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
ta4j-core = { group = "org.ta4j", name = "ta4j-core", version.ref = "ta4j" }
commons-math3 = { group = "org.apache.commons", name = "commons-math3", version.ref = "commonsMath" }
kotlin-dataframe = { group = "org.jetbrains.kotlinx", name = "dataframe", version.ref = "dataframe" }
xchart = { group = "org.knowm.xchart", name = "xchart", version.ref = "xchart" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
